### ISSUE TITLE
Не работает "tooltip"

### ISSUE THREAD

**Issue by zvermafia** [bahdall/restoran#7]
Добавил "data" параметры, активировал $('selector').tooltip(). Но все равно при наведение курсора на кнопку (ссылку) не появляется tooltip (ни какой реакций).

Bootstrap.js ругался на версию jQuery, упгрейдил jQuery до последный версий. Реакция есть, кнопка мерцает.

Эти изменения только в ветке "bugs".

**Comment by mashrab** [comment]
Где ты хочешь использовать тултип?

**Comment by zvermafia** [comment]
Top bar'е в ссылке login/registration, можно посмотреть в последнем коммите в dev ветке.
Можете сразу запуллить к себе в локальку и посмотреть что происходит...

**Comment by zvermafia** [comment]
![enter_icon](https://cloud.githubusercontent.com/assets/7254584/9108836/65ada7fa-3c4a-11e5-86f6-0fe9d0ea77dc.png)

**Comment by mashrab** [comment]
давай https://github.com/chinchang/hint.css эту попробуем, boostrap зб ))

**Comment by zvermafia** [comment]
С этим тоже были проблемы, но они решились. Спасибо!
